<?php 
	$date = "April 2 &amp; 3, 2019";
	$font = '<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> ';
	$wk_date = "April 1, 2019";
	$hk_date = "April 4, 2019";
	$reglink = "https://perfmatters.lilregie.com";
	$year = "2019";

    $tagline = 'The building blocks of web performance: Getting to "fast enough?"';

	$nav = 	"<ul>\r\n" .
			"<li><a href=\"/talks\"><span>Speakers &amp; Talks</span></a></li>\r\n" .
			"<li><a href=\"/workshop\"><span>Workshop</span></a></li>\r\n" .
			"<li><a href=\"/venue\"><span>Venue</span></a></li>\r\n" .
			"<li><a href=\"/diversity\"><span>Diversity</span></a></li>\r\n" .
			'<li class="cta"><a href="https://perfmatters.lilregie.com" title="Register Now"><span>REGISTER</span></a></li>' .
		"</ul>\r\n";

		$nav2 = "<ul>\r\n" .
			"<li><a href=\"../talks\"><span>Speakers &amp; Talks</span></a></li>\r\n" .
			"<li><a href=\"/workshop\"><span>Workshop</span></a></li>\r\n" .
			"<li><a href=\"/venue\">Venue</span></a></li>\r\n" .
			"<li><a href=\"/diversity\"><span>Diversity</span></a></li>\r\n" .
			'<li class="cta"><a href="https://perfmatters.lilregie.com" title="Register Now"><span>REGISTER</span></a></li>\r\n' .
		"</ul>\r\n";

	$footer = "<small>&copy; 2019 <a href=\"/\">#PerfMatters: Web Performance Conference</a> &middot; <a href=\"/code/\">Code of Conduct</a> &middot; <a href='/support/'>Become a sponsor</a> </small>";

	$logo = "	<figure class=\"logo\">\r\n<a href=\"/\">#PerfMatters</a><small>April 2 &amp; 3, 2019<br/>Redwood City, CA</small>\r\n</figure>";

	$logo = '';

	$form = "https://goo.gl/forms/uaPxPCPWKbJA7Wni1";
	
	$reg = '<div class="registration">
		<p><a href="' . $reglink . '" title="Register Now" class="cta" style="margin: 1.5em auto 0.5em;">Register Now</a> <br/><a href="/diversity/">Scholarship Info</a></p><div>
	<table>
	<caption>Conference (Only)</caption>
		<thead><tr>
			<th width="38%">Ticket Type</th>
			<th width="25%">Sale Ends</th>
			<th width="25%">Available</th>
			<th width="12%">Cost</th>
		</tr></thead>
		<tbody>
		<tr>
			<td>Blind Bird</td>
			<td>October 30, 2018</td>
			<td>EXPIRED</td>
			<td>$329</td>
		</tr>
		<tr>
			<td>Very Early Bird</td>
			<td>November 30, 2018</td>
			<td>EXPIRED</td>
			<td>$379</td>
		</tr>
		<tr  class="active">
			<td>Early Bird</td>
			<td>January 31, 2019</td>
			<td>AVAILABLE</td>
			<td>$429</td>
		</tr>
		<tr>
			<td>Regular Ticket</td>
			<td>March 14, 2019</td>
			<td>NOT YET</td>
			<td>$479</td>
		</tr>
		<tr>
			<td>Conference Only</td>
			<td>April 3, 2019</td>
			<td>NOT YET</td>
			<td>$579</td>
		</tr>
	</tbody>
	</table>
	
	
<table>
	<caption>Conference &amp; Hackathon</caption>
		<thead><tr>
			<th width="38%">Ticket Type</th>
			<th width="25%">Sale Ends</th>
			<th width="25%">Available</th>
			<th width="12%">Cost</th>
		</tr></thead>
		<tbody>
		<tr>
			<td>Blind Bird</td>
			<td>October 30, 2018</td>
			<td>EXPIRED</td>
			<td>$369</td>
		</tr>
		<tr>
			<td>Very Early Bird</td>
			<td>November 30, 2018</td>
			<td>EXPIRED</td>
			<td>$419</td>
		</tr>
		<tr   class="active">
			<td>Early Bird</td>
			<td>January 31, 2019</td>
			<td>AVAILABLE</td>
			<td>$469</td>
		</tr>
		<tr>
			<td>Regular Ticket</td>
			<td>March 14, 2019</td>
			<td>NOT YET</td>
			<td>$529</td>
		</tr>
		<tr>
			<td>You\'re late</td>
			<td>March 30, 2019</td>
			<td>NOT YET</td>
			<td>$654</td>
		</tr>
	</tbody>
	</table>	
	
	
	<table>
	<caption>Conference &amp; Workshop</caption>
		<thead><tr>
			<th width="38%">Ticket Type</th>
			<th width="25%">Sale Ends</th>
			<th width="25%">Available</th>
			<th width="12%">Cost</th>
		</tr></thead>
		<tbody>
		<tr>
			<td>Blind Bird</td>
			<td>October 30, 2018</td>
			<td>EXPIRED</td>
			<td>$578</td>
		</tr>
		<tr>
			<td>Very Early Bird</td>
			<td>November 30, 2018</td>
			<td>EXPIRED</td>
			<td>$708</td>
		</tr>
		<tr  class="active">
			<td>Early Bird</td>
			<td>January 31, 2019</td>
			<td>AVAILABLE</td>
			<td>$808</td>
		</tr>
		<tr>
			<td>Regular Ticket</td>
			<td>March 14, 2019</td>
			<td>NOT YET</td>
			<td>$908</td>
		</tr>
		<tr>
			<td>You\'re late!</td>
			<td>April 1, 2019</td>
			<td>NOT YET</td>
			<td>$1,108</td>
		</tr>
	</tbody>
	</table>
	</div>
		<p><a href="' . $reglink . '" title="Register Now" class="cta" style="margin: 1.5em auto 0">Register Now</a> <br/>&nbsp; <a href="/diversity/">Scholarship Info</a></div>';

?>