<?php 
	$date = "March 27-28, 2018";

	$wk_date = "March 26, 2018";

	$nav = 	"<ul>\r\n" .
			"<li><a href=\"/#speakers\">Speakers</a></li>\r\n" .
			"<li><a href=\"/sponsors\">Sponsors</a></li>\r\n" .
			"<li><a href=\"/venue\">Venue</a></li>\r\n" .
			"<li class=\"cta\"><a href=\"#reg\">Register</a></li>\r\n" .
		"</ul>\r\n";

		$nav2 = "<ul>\r\n" .
			"<li><a href=\"../#speakers\">Speakers</a></li>\r\n" .
			"<li><a href=\"/sponsors\">Sponsors</a></li>\r\n" .
			"<li><a href=\"/venue\">Venue</a></li>\r\n" .
			'<li class="cta"><a href="https://perfmattersconf.lilregie.com" title="Register Now">REGISTER</a></li>\r\n' .
		"</ul>\r\n";

	$footer = "<small>&copy; 2018 <a href=\"/\">#PerfMatters: Web Performance Conference</a> &middot; <a href=\"/code/\">Code of Conduct</a></small>";

	$logo = "	<figure class=\"logo\">\r\n<a href=\"/\">#PerfMatters</a><small>March 27 &amp; 28, 2018<br/>Redwood City, CA</small>\r\n</figure>";

	$form = "https://goo.gl/forms/iyRBhbcxpnjY2llW2";

?>