<?php 
	$date = "March 27-28, 2018";

	$wk_date = "March 26, 2018";

	$nav = 	"<ul>\r\n" .
			"<li><a href=\"/#speakers\">Speakers</a></li>\r\n" .
			"<li><a href=\"/talks\">Talks</a></li>\r\n" .
			"<li><a href=\"/sponsors\">Sponsors</a></li>\r\n" .
			"<li><a href=\"/venue\">Venue</a></li>\r\n" .
			"<li class=\"cta\"><a href=\"/#reg\">Register</a></li>\r\n" .
		"</ul>\r\n";

		$nav2 = "<ul>\r\n" .
			"<li><a href=\"../#speakers\">Speakers</a></li>\r\n" .
			"<li><a href=\"../talks\">Talks</a></li>\r\n" .
			"<li><a href=\"/sponsors\">Sponsors</a></li>\r\n" .
			"<li><a href=\"/venue\">Venue</a></li>\r\n" .
			'<li class="cta"><a href="https://perfmattersconf.lilregie.com" title="Register Now">REGISTER</a></li>\r\n' .
		"</ul>\r\n";

	$footer = "<small>&copy; 2018 <a href=\"/\">#PerfMatters: Web Performance Conference</a> &middot; <a href=\"/code/\">Code of Conduct</a></small>";

	$logo = "	<figure class=\"logo\">\r\n<a href=\"/\">#PerfMatters</a><small>March 27 &amp; 28, 2018<br/>Redwood City, CA</small>\r\n</figure>";

	$form = "https://goo.gl/forms/iyRBhbcxpnjY2llW2";
	
	$reg = '<table>
		<thead><tr>
			<th>Ticket Type</th>
			<th>Available Through</th>
			<th>Cost</th>
		</tr></thead>
		<tbody>
		<tr style="opacity: 0.15">
			<td><strike>Blind Bird</strike></td>
			<td><strike>September 30, 2017</strike></td>
			<td><strike>$239</strike></td>
		</tr>
		<tr style="opacity: 0.15">
			<td><strike>Very Early Bird</strike></td>
			<td><strike>November 30, 2017</strike></td>
			<td><strike>$329</strike></td>
		</tr>
		<tr>
			<td>Early Bird</td>
			<td>January 31, 2018</td>
			<td>$399</td>
		</tr><tr>
			<td>Workshop Only</td>
			<td>January 31, 2018</td>
			<td>$200</td>
		</tr>
        <tr>
			<td>Conference &amp; Workshop</td>
			<td>January 31, 2018</td>
			<td>$549</td>
		</tr>
		<tr style="opacity: 0.35">
			<td>Regular Ticket</td>
			<td>March 24, 2018</td>
			<td>$479</td>
		</tr><tr style="opacity: 0.35">
			<td>Workshop Only</td>
			<td>March 24, 2018</td>
			<td>$250</td>
		</tr>
        <tr style="opacity: 0.35">
			<td>Conference &amp; Workshop</td>
			<td>March 24, 2018</td>
			<td>$679</td>
		</tr>
		<tr style="opacity: 0.15">
			<td>Conference Only</td>
			<td>At the venue</td>
			<td>$579</td></tr><tr style="opacity: 0.15">
			<td>Workshop Only</td>
			<td>At the venue</td>
			<td>$300</td>
		</tr>
		<tr>
			<td colspan="3"><a href="https://perfmattersconf.lilregie.com" title="Register Now" class="cta">Register Now</a></td>
		</tr>
	</tbody></table>';

?>